CGFP/Models/CGFPContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace CGFP.Models
{
    public class CGFPContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public CGFPContext() : base("name=CGFPContext")
        {
        }

        public System.Data.Entity.DbSet<CGFP.Models.ProjectsModel> ProjectsModels { get; set; }
    }
}

CGFP/Models/ProjectsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CGFP.Models
{
    public class ProjectsModel

    {

        [Key]
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string DescripProject { get; set; }
        public string Image { get; set; }
        public string GitAddress { get; set; }

    }
}

CGFP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CGFP.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CGFP/Controllers/ProjectsModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CGFP.Models;

namespace CGFP.Controllers
{
    public class ProjectsModelsController : Controller
    {
        private CGFPContext db = new CGFPContext();

        // GET: ProjectsModels
        public ActionResult Index()
        {
            return View(db.ProjectsModels.ToList());
        }

        // GET: ProjectsModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectsModel projectsModel = db.ProjectsModels.Find(id);
            if (projectsModel == null)
            {
                return HttpNotFound();
            }
            return View(projectsModel);
        }

        // GET: ProjectsModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProjectsModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectId,ProjectName,DescripProject,Image,GitAddress")] ProjectsModel projectsModel)
        {
            if (ModelState.IsValid)
            {
                db.ProjectsModels.Add(projectsModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projectsModel);
        }

        // GET: ProjectsModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectsModel projectsModel = db.ProjectsModels.Find(id);
            if (projectsModel == null)
            {
                return HttpNotFound();
            }
            return View(projectsModel);
        }

        // POST: ProjectsModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectId,ProjectName,DescripProject,Image,GitAddress")] ProjectsModel projectsModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectsModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projectsModel);
        }

        // GET: ProjectsModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectsModel projectsModel = db.ProjectsModels.Find(id);
            if (projectsModel == null)
            {
                return HttpNotFound();
            }
            return View(projectsModel);
        }

        // POST: ProjectsModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProjectsModel projectsModel = db.ProjectsModels.Find(id);
            db.ProjectsModels.Remove(projectsModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CGFP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}




<div class="col-md-4 head3">
    <h3>About me and my professional experience:  </h3>
    <p>
        Passionate, self-directed, and organized professional with extensive experience in technology.
        Motivated with a strong work ethic toward improving technology and software programs.
     <p>
         A master coach with 14 years of experience in leading and training in the latest technological advancements.
    </p>
    <p>
        Thrives within project management driven environments utlizing excellent collaboration skills.
    </p>
    <p>
        I found working with front end design compliments my artisitic abilities in the visual arts.
    </p>

</div>
<div class="col-md-4 head3">
    <h3>Exeperienced with the following:</h3>
    <div>
        <ul>
            <li>HTML/CSS</li>
            <li>MVC/Razor</li>
            <li>Bootstrap</li>
            <li>C#</li>
            <li>SQL</li>
        </ul>
    </div>
    <div>
        <h3>Proficient:</h3>
        <ul>
            <li>IT Support</li>
            <li>Instructional Learning Systems</li>
            <li>Project Management </li>
            <li>Network Planning </li>
            <li>Professional Development</li>
            <li>PowerSchool</li>
        </ul>

    </div>



</div>
<div class="col-md-4 about vertical-center img-circle ">

</div>

CGFP/Views/Home/Contact.cshtml
   

<address>
    <p> If you like to contact me in regards contract work or full-time employment.</p>
    <p> Please feel free to email at the following link below</p>
    <strong>Contact information:</strong>
    <div>
        <a href="mailto:cgmeiit@gmail.com">Email address</a>
    </div>
</address>

CGFP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<div class="col-md-12 brder1 mainpic img-responsive img-circle1">
    <div >
        <h1 class="head1">Hello! I'm Cynthia </h1>
        <div >
            <p class="head2">This is my design community.</p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 bgImage1 vertical-center img-circle ">
        
        <p class="btn head brder1">@Html.ActionLink("Projects", "Index", "ProjectsModels")</p>
       
    </div>
    <div class="col-md-4 bgImage2 vertical-center img-circle" >
                
        <p><a class="btn head brder1"href="https://github.com/cgmeiit" >GitHub </a></p>

    </div>
    <div class="col-md-4 bgImage3 vertical-center img-circle">
        
        <p><a class="btn head brder1"href="https://www.linkedin.com/home?trk=nav_responsive_tab_home">Linkdyn</a></p>

    </div>
</div>

CGFP/Views/ProjectsModels/Create.cshtml
@model CGFP.Models.ProjectsModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectsModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripProject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripProject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripProject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GitAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GitAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GitAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CGFP/Views/ProjectsModels/Delete.cshtml
@model CGFP.Models.ProjectsModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescripProject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescripProject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GitAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GitAddress)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CGFP/Views/ProjectsModels/Details.cshtml
@model CGFP.Models.ProjectsModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProjectsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescripProject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescripProject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GitAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GitAddress)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProjectId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CGFP/Views/ProjectsModels/Edit.cshtml
@model CGFP.Models.ProjectsModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectsModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProjectId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripProject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripProject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripProject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GitAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GitAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GitAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CGFP/Views/ProjectsModels/Index.cshtml
@model IEnumerable<CGFP.Models.ProjectsModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@foreach (var item in Model)
{

    /*making squares*/
    <div class="col-md-3 square bgImage vertical-center " style="border-color:#420808;border-width:4px;border-style:solid;margin-right:20px;margin-bottom:20px;background-image: url('@item.Image')">
        <div class="content">
            <div class="table">
                <a href="@item.GitAddress" target="_blank">
                    <div class="Table-cell">
                        <div class="overlay">
                            <h2>@item.ProjectName</h2>
                            <p>@item.DescripProject</p>
                        </div>

                    </div>
                </a>
            </div>
        </div>
    </div>
}










<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescripProject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GitAddress)
    </th>
</tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectName)
        </td>
        <td>
            @Html.DisplayFor(model => item.Image)
            @*<img src="@item.Image" />*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DescripProject)
        </td>
        <td>
            <a href="@item.GitAddress">@item.GitAddress</a>
        </td>
        <td>

            @Html.ActionLink("Edit", "Edit", new { id = item.ProjectId }) |
            @Html.ActionLink("Details", "Details", new { id = item.ProjectId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ProjectId })
        </td>
    </tr>
}

</table>


        

CGFP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Delius' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
</head>
<body style="background-color:#dcc7b2;">
                <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav head">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>         
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>